# Generated by Django 4.1.1 on 2022-09-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_customuser_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="about",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="display_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
