# Generated by Django 4.1.1 on 2022-10-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_customuser_about_customuser_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
