# Generated by Django 4.1.1 on 2022-10-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_customuser_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.CharField(
                blank=True, default="United States", max_length=200, null=True
            ),
        ),
    ]
