# Generated by Django 4.1.1 on 2022-09-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="initials",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
