# Generated by Django 4.1.1 on 2022-09-23 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community", "0002_community_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="community_author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
