# Generated by Django 4.1.1 on 2022-09-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_community_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
