# Generated by Django 4.1.1 on 2022-10-08 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("setting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="setting_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
