# Generated by Django 4.1.1 on 2022-09-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upvote", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="upvote",
            name="action",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
